2023-10-07 15:18:18,286 INFO [streaming_server.py:808] {'encoder': './sherpa-onnx-streaming-zipformer-en-2023-06-21/encoder-epoch-99-avg-1.int8.onnx', 'decoder': './sherpa-onnx-streaming-zipformer-en-2023-06-21/decoder-epoch-99-avg-1.int8.onnx', 'joiner': './sherpa-onnx-streaming-zipformer-en-2023-06-21/joiner-epoch-99-avg-1.int8.onnx', 'paraformer_encoder': None, 'paraformer_decoder': None, 'tokens': './sherpa-onnx-streaming-zipformer-en-2023-06-21/tokens.txt', 'sample_rate': 16000, 'feat_dim': 80, 'provider': 'cpu', 'decoding_method': 'greedy_search', 'num_active_paths': 4, 'use_endpoint': 1, 'rule1_min_trailing_silence': 2.4, 'rule2_min_trailing_silence': 1.2, 'rule3_min_utterance_length': 20, 'hotwords_file': '', 'hotwords_score': 1.5, 'port': 6006, 'nn_pool_size': 1, 'max_batch_size': 50, 'max_wait_ms': 10, 'max_message_size': 1048576, 'max_queue_size': 32, 'max_active_connections': 500, 'num_threads': 2, 'certificate': None, 'doc_root': 'web'}
2023-10-07 15:18:20,247 INFO [streaming_server.py:625] No certificate provided
2023-10-07 15:18:20,248 INFO [server.py:711] server listening on 0.0.0.0:6006
2023-10-07 15:18:20,250 INFO [server.py:711] server listening on [::]:6006
2023-10-07 15:18:20,250 INFO [streaming_server.py:651] Please visit one of the following addresses:

  http://localhost:6006

Since you are not providing a certificate, you cannot use your microphone from within the browser using public IP addresses. Only localhost can be used.You also cannot use 0.0.0.0 or 127.0.0.1
2023-10-07 15:18:26,612 INFO [server.py:233] connection failed (200 OK)
2023-10-07 15:18:26,613 INFO [server.py:268] connection closed
2023-10-07 15:18:26,698 INFO [server.py:233] connection failed (200 OK)
2023-10-07 15:18:26,699 INFO [server.py:268] connection closed
2023-10-07 15:18:26,703 INFO [server.py:233] connection failed (200 OK)
2023-10-07 15:18:26,704 INFO [server.py:233] connection failed (200 OK)
2023-10-07 15:18:26,705 INFO [server.py:233] connection failed (200 OK)
2023-10-07 15:18:26,705 INFO [server.py:233] connection failed (200 OK)
2023-10-07 15:18:26,706 INFO [server.py:268] connection closed
2023-10-07 15:18:26,706 INFO [server.py:268] connection closed
2023-10-07 15:18:26,706 INFO [server.py:268] connection closed
2023-10-07 15:18:26,706 INFO [server.py:268] connection closed
2023-10-07 15:18:26,762 INFO [server.py:233] connection failed (200 OK)
2023-10-07 15:18:26,763 INFO [server.py:268] connection closed
2023-10-07 15:18:26,767 INFO [server.py:233] connection failed (200 OK)
2023-10-07 15:18:26,769 INFO [server.py:233] connection failed (200 OK)
2023-10-07 15:18:26,770 INFO [server.py:268] connection closed
2023-10-07 15:18:26,770 INFO [server.py:268] connection closed
2023-10-07 15:18:26,802 INFO [server.py:233] connection failed (200 OK)
2023-10-07 15:18:26,803 INFO [server.py:268] connection closed
2023-10-07 15:18:28,388 INFO [server.py:646] connection open
2023-10-07 15:18:28,388 INFO [streaming_server.py:692] Connected: ('::1', 53499, 0, 0). Number of connections: 1/500
2023-10-07 15:18:32,114 INFO [streaming_server.py:676] Disconnected: ('::1', 53499, 0, 0). Number of connections: 0/500
2023-10-07 15:18:32,114 ERROR [server.py:242] connection handler failed
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websockets/legacy/server.py", line 240, in handler
    await self.ws_handler(self)
  File "/Users/fawazahamedshaik/github/ASR/Interactive_ASR/./streaming_server.py", line 669, in handle_connection
    await self.handle_connection_impl(socket)
  File "/Users/fawazahamedshaik/github/ASR/Interactive_ASR/./streaming_server.py", line 724, in handle_connection_impl
    text = generate(message['text'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fawazahamedshaik/github/ASR/Interactive_ASR/./streaming_server.py", line 104, in generate
    out=pn(f"""{result}""")
        ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/haystack/nodes/prompt/prompt_node.py", line 140, in __call__
    return self.prompt(self.default_prompt_template, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/haystack/nodes/prompt/prompt_node.py", line 179, in prompt
    output = self.prompt_model.invoke(prompt, **kwargs_copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/haystack/nodes/prompt/prompt_model.py", line 111, in invoke
    output = self.model_invocation_layer.invoke(prompt=prompt, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/haystack/nodes/prompt/invocation_layer/hugging_face_inference.py", line 137, in invoke
    raise ValueError(
ValueError: No prompt provided. Model mistralai/Mistral-7B-Instruct-v0.1 requires prompt.Make sure to provide prompt in kwargs.
2023-10-07 15:18:32,121 INFO [server.py:268] connection closed
